services:
  api:
    build: ./backend/WIB.API
    environment:
      ASPNETCORE_URLS: http://+:8080
    ports:
      - "8080:8080"
    depends_on:
      - db
  worker:
    build: ./backend/WIB.Worker
    depends_on:
      - db
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: wib
      POSTGRES_USER: wib
      POSTGRES_PASSWORD: wib
  redis:
    image: redis:7-alpine
  minio:
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: wib
      MINIO_ROOT_PASSWORD: wibsecret
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
  ocr:
    build: ./services/ocr
    ports:
      - "8081:8081"
  ml:
    build: ./services/ml
    ports:
      - "8082:8082"
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
