services:
  api:
    build:
      context: ./backend
      dockerfile: WIB.API/Dockerfile
    environment:
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__Default: Host=db;Database=wib;Username=wib;Password=wib
      Minio__Endpoint: minio:9000
      Minio__AccessKey: wib
      Minio__SecretKey: wibsecret
      Redis__Connection: redis:6379
      Ocr__Endpoint: http://ocr:8081
      Ml__Endpoint: http://ml:8082
      Qdrant__Endpoint: http://qdrant:6333
    ports:
      - "8080:8080"
    depends_on:
      - db
      - minio
      - redis
      - ocr
      - ml
      - qdrant
  worker:
    build:
      context: ./backend
      dockerfile: WIB.Worker/Dockerfile
    environment:
      ConnectionStrings__Default: Host=db;Database=wib;Username=wib;Password=wib
      Minio__Endpoint: minio:9000
      Minio__AccessKey: wib
      Minio__SecretKey: wibsecret
      Redis__Connection: redis:6379
      Ocr__Endpoint: http://ocr:8081
      Ml__Endpoint: http://ml:8082
      Qdrant__Endpoint: http://qdrant:6333
    depends_on:
      - db
      - minio
      - redis
      - ocr
      - ml
      - qdrant
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: wib
      POSTGRES_USER: wib
      POSTGRES_PASSWORD: wib
    volumes:
      - ./.data/db:/var/lib/postgresql/data
  redis:
    image: redis:7
  minio:
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: wib
      MINIO_ROOT_PASSWORD: wibsecret
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./.data/minio:/data
  ocr:
    build: ./services/ocr
    ports:
      - "8081:8081"
  ml:
    build: ./services/ml
    ports:
      - "8082:8082"
    volumes:
      - ./.data/models:/app/models
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
  wib-wmc:
    build:
      context: ./frontend
      args:
        APP_PATH: apps/wib-wmc
    environment:
      API_URL: http://api:8080
      OCR_URL: http://ocr:8081
      ML_URL: http://ml:8082
      QDRANT_URL: http://qdrant:6333
      MINIO_URL: http://minio:9000
    ports:
      - "4200:80"
    depends_on:
      - api
      - ocr
      - ml
      - qdrant
      - minio
  wib-devices:
    build:
      context: ./frontend
      args:
        APP_PATH: apps/wib-devices
    environment:
      API_URL: http://api:8080
    ports:
      - "4201:80"
    depends_on:
      - api
