name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
      - run: dotnet build backend/WIB.sln
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm run lint --prefix frontend
      - run: npm run check:angular
      - run: pip install -r services/ocr/requirements.txt -r services/ml/requirements.txt
      - run: python -m pytest services/ocr/tests services/ml/tests
